# Generated by Django 5.1.1 on 2024-09-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_options_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, max_length=11, unique=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, max_length=11)),
                ('name', models.TextField(max_length=32, unique=True)),
                ('variety', models.TextField(blank=True, max_length=32)),
                ('cycle_duration', models.IntegerField(blank=True)),
                ('client_id', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
