# Generated by Django 5.1.1 on 2024-09-15 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, max_length=11, unique=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, max_length=11)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cultivo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
