# Generated by Django 5.1.1 on 2024-09-15 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cultivo',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='api.cultivo'),
        ),
    ]
