# Generated by Django 5.1.1 on 2024-09-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_client_cultivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cultivo',
        ),
    ]
