# Generated by Django 5.1.1 on 2024-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cultivo_cycle_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='cycle_duration',
            field=models.IntegerField(null=True),
        ),
    ]
