# Generated by Django 5.1.1 on 2024-09-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cultivo_cycle_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
    ]
