# Generated by Django 5.1.1 on 2024-09-19 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cultivo_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
