# Generated by Django 5.1.1 on 2024-09-19 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_client_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_id',
            new_name='user',
        ),
    ]
